services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hamdard-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env.dev   # env مخصوص dev سرور
    restart: unless-stopped
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hamdard-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.dev
    restart: unless-stopped
    depends_on:
      - backend
