services:
  backend:
    image: ghcr.io/faeizhamdard22/hamdard-hospital-backend:dev
    container_name: hamdard-backend
    ports:
      - "5000:5000"
    env_file:
      - ./.env.dev
    restart: unless-stopped

  frontend:
    image: ghcr.io/faeizhamdard22/hamdard-hospital-frontend:dev
    container_name: hamdard-frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env.dev
    depends_on:
      - backend
    restart: unless-stopped
